-- Migration: Add Referral System
-- This script adds referral tracking and fee recording capabilities

-- 1. Add referral fields to users table
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS referral_code TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS referred_by_user_id INTEGER REFERENCES users(id_user);

-- Create index for faster referral code lookups
CREATE INDEX IF NOT EXISTS idx_users_referral_code ON users(referral_code);
CREATE INDEX IF NOT EXISTS idx_users_referred_by ON users(referred_by_user_id);

-- 2. Create fees table to track all fees generated
CREATE TABLE IF NOT EXISTS fees (
  id_fee SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id_user) ON DELETE CASCADE,
  trade_id INTEGER REFERENCES trades(id_trade) ON DELETE SET NULL,
  fee_amount NUMERIC(18, 6) NOT NULL CHECK (fee_amount >= 0),
  notional_value NUMERIC(18, 6) NOT NULL CHECK (notional_value >= 0),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_fees_user_id ON fees(user_id);
CREATE INDEX IF NOT EXISTS idx_fees_trade_id ON fees(trade_id);
CREATE INDEX IF NOT EXISTS idx_fees_created_at ON fees(created_at DESC);

-- 3. Create referral_earnings table to track commissions
CREATE TABLE IF NOT EXISTS referral_earnings (
  id_earning SERIAL PRIMARY KEY,
  referrer_user_id INTEGER NOT NULL REFERENCES users(id_user) ON DELETE CASCADE,
  referred_user_id INTEGER NOT NULL REFERENCES users(id_user) ON DELETE CASCADE,
  fee_id INTEGER NOT NULL REFERENCES fees(id_fee) ON DELETE CASCADE,
  earning_amount NUMERIC(18, 6) NOT NULL CHECK (earning_amount >= 0),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
  paid_at TIMESTAMPTZ,
  distribution_batch_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_referral_earnings_referrer ON referral_earnings(referrer_user_id);
CREATE INDEX IF NOT EXISTS idx_referral_earnings_referred ON referral_earnings(referred_user_id);
CREATE INDEX IF NOT EXISTS idx_referral_earnings_fee ON referral_earnings(fee_id);
CREATE INDEX IF NOT EXISTS idx_referral_earnings_created_at ON referral_earnings(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_referral_earnings_status ON referral_earnings(status);
CREATE INDEX IF NOT EXISTS idx_referral_earnings_batch ON referral_earnings(distribution_batch_id);

-- Add comments for documentation
COMMENT ON TABLE fees IS 'Tracks all trading fees generated by users (1% of notional value)';
COMMENT ON TABLE referral_earnings IS 'Tracks referral commissions earned (30% of referred users fees). Paid monthly.';
COMMENT ON COLUMN users.referral_code IS 'Unique referral code for each user';
COMMENT ON COLUMN users.referred_by_user_id IS 'User who referred this user (if any)';
COMMENT ON COLUMN referral_earnings.status IS 'Payment status: pending (not yet paid) or paid (distributed)';
COMMENT ON COLUMN referral_earnings.paid_at IS 'Timestamp when the earning was paid out';
COMMENT ON COLUMN referral_earnings.distribution_batch_id IS 'Batch ID for monthly distribution (e.g. 2025-10)';

