import crypto from "crypto";
import sql from "../db/db.js";
import { logger } from "../utils/logger.js";

/**
 * Generate a unique referral code
 * @returns {Promise<string>} 8-character alphanumeric code
 */
export async function generateReferralCode() {
  let attempts = 0;
  const maxAttempts = 10;

  while (attempts < maxAttempts) {
    // Generate 8-character alphanumeric code (uppercase)
    const code = crypto
      .randomBytes(6)
      .toString("base64")
      .replace(/[^A-Za-z0-9]/g, "")
      .toUpperCase()
      .substring(0, 8);

    // Check if code already exists
    const [existing] = await sql`
      SELECT id_user FROM users WHERE referral_code = ${code}
    `;

    if (!existing) {
      return code;
    }

    attempts++;
  }

  // Fallback: use timestamp-based code if all random attempts fail
  const fallback = Date.now().toString(36).toUpperCase().substring(0, 8);
  logger.warn("Using fallback referral code after max attempts", { fallback });
  return fallback;
}

/**
 * Find user by referral code (case-insensitive)
 * @param {string} referralCode
 * @returns {Promise<Object|null>} User object or null
 */
export async function getUserByReferralCode(referralCode) {
  if (!referralCode) return null;

  const [user] = await sql`
    SELECT id_user, telegram_id, username, referral_code
    FROM users
    WHERE UPPER(referral_code) = UPPER(${referralCode})
  `;

  return user || null;
}

/**
 * Record a fee generated by a user
 * @param {number} userId - Database user ID
 * @param {number|null} tradeId - Database trade ID (optional)
 * @param {number} feeAmount - Fee amount in USDC
 * @param {number} notionalValue - Trade notional value in USDC
 * @returns {Promise<Object>} Inserted fee record
 */
export async function recordFee(userId, tradeId, feeAmount, notionalValue) {
  const [fee] = await sql`
    INSERT INTO fees (user_id, trade_id, fee_amount, notional_value)
    VALUES (${userId}, ${tradeId}, ${feeAmount}, ${notionalValue})
    RETURNING *
  `;

  logger.info("Fee recorded", { userId, tradeId, feeAmount, notionalValue });
  return fee;
}

/**
 * Record referral earnings for a referrer
 * @param {number} referrerUserId - Database user ID of referrer
 * @param {number} referredUserId - Database user ID of referred user
 * @param {number} feeId - Fee record ID
 * @param {number} earningAmount - Commission amount in USDC
 * @returns {Promise<Object>} Inserted earning record
 */
export async function recordReferralEarning(
  referrerUserId,
  referredUserId,
  feeId,
  earningAmount
) {
  const [earning] = await sql`
    INSERT INTO referral_earnings (
      referrer_user_id,
      referred_user_id,
      fee_id,
      earning_amount
    )
    VALUES (${referrerUserId}, ${referredUserId}, ${feeId}, ${earningAmount})
    RETURNING *
  `;

  logger.info("Referral earning recorded", {
    referrerUserId,
    referredUserId,
    feeId,
    earningAmount,
  });
  return earning;
}

/**
 * Process fee and referral commission for a trade
 * @param {number} userId - Database user ID
 * @param {number|null} tradeId - Database trade ID
 * @param {number} notionalValue - Trade notional value in USDC
 * @param {number} feeRate - Fee rate (default 0.01 = 1%)
 * @param {number} referralCommissionRate - Commission rate (default 0.30 = 30%)
 * @returns {Promise<Object>} Object with fee and earning info
 */
export async function processFeeAndReferral(
  userId,
  tradeId,
  notionalValue,
  feeRate = 0.01,
  referralCommissionRate = 0.3
) {
  // Calculate fee (1% of notional value)
  const feeAmount = notionalValue * feeRate;

  // Record the fee
  const fee = await recordFee(userId, tradeId, feeAmount, notionalValue);

  // Check if user has a referrer
  const [user] = await sql`
    SELECT referred_by_user_id FROM users WHERE id_user = ${userId}
  `;

  let referralEarning = null;

  if (user && user.referred_by_user_id) {
    // Calculate referral commission (30% of fee)
    const commissionAmount = feeAmount * referralCommissionRate;

    // Record the referral earning
    referralEarning = await recordReferralEarning(
      user.referred_by_user_id,
      userId,
      fee.id_fee,
      commissionAmount
    );
  }

  return {
    fee,
    referralEarning,
    feeAmount,
    commissionAmount: referralEarning ? referralEarning.earning_amount : 0,
  };
}

/**
 * Get referral statistics for a user
 * @param {number} userId - Database user ID
 * @returns {Promise<Object>} Referral stats
 */
export async function getReferralStats(userId) {
  // Get total referred users count
  const [countResult] = await sql`
    SELECT COUNT(*) as total_referred
    FROM users
    WHERE referred_by_user_id = ${userId}
  `;

  // Get pending earnings (current month)
  const [pendingResult] = await sql`
    SELECT COALESCE(SUM(earning_amount), 0) as pending_earnings
    FROM referral_earnings
    WHERE referrer_user_id = ${userId} AND status = 'pending'
  `;

  // Get total paid earnings (all time)
  const [paidResult] = await sql`
    SELECT COALESCE(SUM(earning_amount), 0) as paid_earnings
    FROM referral_earnings
    WHERE referrer_user_id = ${userId} AND status = 'paid'
  `;

  // Get last distribution date
  const [lastDistribution] = await sql`
    SELECT paid_at
    FROM referral_earnings
    WHERE referrer_user_id = ${userId} AND status = 'paid'
    ORDER BY paid_at DESC
    LIMIT 1
  `;

  // Get list of referred users with their contributions
  const referredUsers = await sql`
    SELECT 
      u.id_user,
      u.telegram_id,
      u.username,
      u.created_at as joined_at,
      COALESCE(SUM(re.earning_amount), 0) as total_contributed
    FROM users u
    LEFT JOIN referral_earnings re ON re.referred_user_id = u.id_user 
      AND re.referrer_user_id = ${userId}
    WHERE u.referred_by_user_id = ${userId}
    GROUP BY u.id_user, u.telegram_id, u.username, u.created_at
    ORDER BY total_contributed DESC, u.created_at DESC
  `;

  return {
    totalReferred: parseInt(countResult.total_referred),
    pendingEarnings: parseFloat(pendingResult.pending_earnings),
    paidEarnings: parseFloat(paidResult.paid_earnings),
    totalEarnings: parseFloat(pendingResult.pending_earnings) + parseFloat(paidResult.paid_earnings),
    lastDistributionDate: lastDistribution?.paid_at || null,
    referredUsers: referredUsers.map((user) => ({
      userId: user.id_user,
      telegramId: user.telegram_id,
      username: user.username,
      joinedAt: user.joined_at,
      totalContributed: parseFloat(user.total_contributed),
    })),
  };
}

/**
 * Generate referral link for a user
 * @param {string} referralCode - User's referral code
 * @param {string} botUsername - Telegram bot username
 * @returns {string} Referral link
 */
export function getReferralLink(referralCode, botUsername) {
  // Remove @ if present
  const cleanUsername = botUsername.replace(/^@/, "");
  return `https://t.me/${cleanUsername}?start=ref_${referralCode}`;
}

/**
 * Get recent earnings history for a referrer
 * @param {number} userId - Database user ID
 * @param {number} limit - Number of recent earnings to fetch
 * @returns {Promise<Array>} Recent earnings
 */
export async function getRecentEarnings(userId, limit = 10) {
  const earnings = await sql`
    SELECT 
      re.id_earning,
      re.earning_amount,
      re.status,
      re.paid_at,
      re.created_at,
      u.username as referred_username,
      u.telegram_id as referred_telegram_id,
      f.notional_value,
      f.fee_amount
    FROM referral_earnings re
    JOIN users u ON u.id_user = re.referred_user_id
    JOIN fees f ON f.id_fee = re.fee_id
    WHERE re.referrer_user_id = ${userId}
    ORDER BY re.created_at DESC
    LIMIT ${limit}
  `;

  return earnings.map((e) => ({
    id: e.id_earning,
    amount: parseFloat(e.earning_amount),
    status: e.status,
    paidAt: e.paid_at,
    createdAt: e.created_at,
    referredUsername: e.referred_username,
    referredTelegramId: e.referred_telegram_id,
    tradeNotional: parseFloat(e.notional_value),
    tradeFee: parseFloat(e.fee_amount),
  }));
}

/**
 * Get all pending earnings grouped by user for distribution
 * @returns {Promise<Array>} List of users with pending earnings
 */
export async function getPendingEarningsForDistribution() {
  const results = await sql`
    SELECT 
      re.referrer_user_id,
      u.telegram_id,
      u.username,
      u.hl_address,
      COALESCE(SUM(re.earning_amount), 0) as total_pending,
      COUNT(re.id_earning) as earnings_count,
      ARRAY_AGG(re.id_earning) as earning_ids
    FROM referral_earnings re
    JOIN users u ON u.id_user = re.referrer_user_id
    WHERE re.status = 'pending'
    GROUP BY re.referrer_user_id, u.telegram_id, u.username, u.hl_address
    HAVING SUM(re.earning_amount) > 0
    ORDER BY total_pending DESC
  `;

  return results.map((r) => ({
    userId: r.referrer_user_id,
    telegramId: r.telegram_id,
    username: r.username,
    walletAddress: r.hl_address,
    totalPending: parseFloat(r.total_pending),
    earningsCount: parseInt(r.earnings_count),
    earningIds: r.earning_ids,
  }));
}

/**
 * Mark earnings as paid
 * @param {Array<number>} earningIds - Array of earning IDs to mark as paid
 * @param {string} batchId - Distribution batch ID (e.g., "2025-10")
 * @returns {Promise<number>} Number of earnings marked as paid
 */
export async function markEarningsAsPaid(earningIds, batchId) {
  if (!earningIds || earningIds.length === 0) {
    return 0;
  }

  const result = await sql`
    UPDATE referral_earnings
    SET 
      status = 'paid',
      paid_at = NOW(),
      distribution_batch_id = ${batchId}
    WHERE id_earning = ANY(${earningIds})
    AND status = 'pending'
  `;

  logger.info(`Marked ${result.count} earnings as paid`, { batchId, count: result.count });
  return result.count;
}

