import sql from "./db.js";
import { logger } from "../utils/logger.js";
import { generateReferralCode } from "../services/referralService.js";

/**
 * Register or update a user in the database.
 * Performs an upsert on telegram_id.
 *
 * Expected database schema (table `users`):
 * - id_user integer (PK, generated by DB)
 * - telegram_id bigint (UNIQUE)
 * - username text
 * - hl_address text
 * - hl_privkey text
 * - created_at timestamptz
 * - last_active timestamptz
 * - hl_agent_pk text
 * - referral_code text (UNIQUE)
 * - referred_by_user_id integer
 *
 * @param {Object} params
 * @param {number|string|bigint} params.telegramId - Telegram user id (int8/bigint)
 * @param {string} [params.username]
 * @param {string} [params.hlAddress]
 * @param {string} [params.hlPrivkey]
 * @param {string} [params.hlAgentPubKey]
 * @param {string} [params.hlAgentPk]
 * @param {number|null} [params.referredByUserId] - Database user ID of referrer
 * @returns {Promise<Object>} Inserted or updated user row
 */
export async function registerUser(
  telegramId,
  username,
  hlAddress,
  hlPrivkey,
  hlAgentPubKey,
  hlAgentPk,
  referredByUserId = null
) {
  if (telegramId === undefined || telegramId === null) {
    logger.info(telegramId);
    throw new Error("telegramId is required");
  }

  // Generate referral code for new users
  const referralCode = await generateReferralCode();

  const [row] = await sql`
      INSERT INTO users (
        telegram_id,
        username,
        hl_address,
        hl_privkey,
        created_at,
        last_active,
        hl_agent_pubKey,
        hl_agent_pk,
        referral_code,
        referred_by_user_id
      ) VALUES (
        ${telegramId},
        ${username},
        ${hlAddress},
        ${hlPrivkey},
        NOW(),
        NOW(),
        ${hlAgentPubKey},
        ${hlAgentPk},
        ${referralCode},
        ${referredByUserId}
      )
      ON CONFLICT (telegram_id) DO UPDATE SET
        username = EXCLUDED.username,
        hl_address = EXCLUDED.hl_address,
        hl_privkey = EXCLUDED.hl_privkey,
        last_active = NOW(),
        hl_agent_pk = EXCLUDED.hl_agent_pk,
        hl_agent_pubKey = EXCLUDED.hl_agent_pubKey
      RETURNING
        id_user, telegram_id, username, hl_address, hl_privkey, created_at, last_active, hl_agent_pk, hl_agent_pubKey, referral_code, referred_by_user_id
    `;

  return row;
}

export async function isUserRegistered(telegramId) {
  const [row] = await sql`
    SELECT * FROM users WHERE telegram_id = ${telegramId}
  `;
  return row !== undefined;
}
