import sql from "./db.js";
import { logger } from "../utils/logger.js";

/**
 * Register or update a user in the database.
 * Performs an upsert on telegram_id.
 *
 * Expected database schema (table `users`):
 * - id_user integer (PK, generated by DB)
 * - telegram_id bigint (UNIQUE)
 * - username text
 * - hl_address text
 * - hl_privkey text
 * - created_at timestamptz
 * - last_active timestamptz
 * - hl_agent_pk text
 *
 * @param {Object} params
 * @param {number|string|bigint} params.telegramId - Telegram user id (int8/bigint)
 * @param {string} [params.username]
 * @param {string} [params.hlAddress]
 * @param {string} [params.hlPrivkey]
 * @param {string} [params.hlAgentPk]
 * @returns {Promise<Object>} Inserted or updated user row
 */
export async function registerUser(
  telegramId,
  username,
  hlAddress,
  hlPrivkey,
  hlAgentPk,
) {
  if (telegramId === undefined || telegramId === null) {
    logger.info(telegramId);
    throw new Error("telegramId is required");
  }

  const [row] = await sql`
      INSERT INTO users (
        telegram_id,
        username,
        hl_address,
        hl_privkey,
        created_at,
        last_active,
        hl_agent_pk
      ) VALUES (
        ${telegramId},
        ${username},
        ${hlAddress},
        ${hlPrivkey},
        NOW(),
        NOW(),
        ${hlAgentPk}
      )
      ON CONFLICT (telegram_id) DO UPDATE SET
        username = EXCLUDED.username,
        hl_address = EXCLUDED.hl_address,
        hl_privkey = EXCLUDED.hl_privkey,
        last_active = NOW(),
        hl_agent_pk = EXCLUDED.hl_agent_pk
      RETURNING
        id_user, telegram_id, username, hl_address, hl_privkey, created_at, last_active, hl_agent_pk
    `;

  return row;
}

export async function isUserRegistered(telegramId) {
  const [row] = await sql`
    SELECT * FROM users WHERE telegram_id = ${telegramId}
  `;
  return row !== undefined;
}
